# 公開するページのURL
baseURL = "https://slicer00.github.io/rokulog"

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true
enableRobotsTXT = true

# ブログのタイトル
title = "ろくログ"

theme = "mainroad"
paginate = 20

# 自己紹介
[Author]
    name = "ろくろー"
    bio = "九州工業大学情報工学部1年生の者です。中学時代からプログラミングに非常に興味があり、この大学に入ってからは様々な言語を学んでいます。"
    avatar = "img/avatar.png"

[Params]
    customCSS = ["css/custom.css"]
    copyright = "Author"
    readmore = true
    authorbox = true
    post_meta = ["date", "categories"]
    twitter_cards = true

# ページのテーマカラー
[Params.style.vars]
  highlightColor = "#ff7f50"

# SNS等のユーザー名
[Params.widgets.social]
  twitter = "slicer0074"
  github = "Slicer00"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "recent", "categories", "taglist", "social"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true